#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
CONTENT_DIR=/opt

useradd adle -s /bin/bash

apt-get install -y python python-crypto 

echo -e 'su - adle -c "python /opt/adleman.py &"\nexit 0' > /etc/rc.local

su - adle -c "python /opt/adleman.py &"
