{% extends "base.phtml" %}
{% block content %} 
<h1>Registration</h1>
{{ msg|raw }}
<form method="POST">
<table>
    <tr>
        <td>Username:</td>
        <td><input type="text" name="username"</td>
    </tr>
    <tr>
        <td>Password:</td>
        <td><input type="password" name="password"</td>
    </tr>
    <tr>
        <td colspan="2"><input type="submit" value="Send" /></td>
    </tr>
</table>
</form>
{% endblock %}
