#!/bin/bash

export DEBIAN_FRONTEND=noninteractive
CONTENT_DIR=/opt

useradd keygen -s /bin/false

apt-get update
apt-get install -y xinetd

chmod +x $CONTENT_DIR/keygen
mv $CONTENT_DIR/xinetd/keygen /etc/xinetd.d

service xinetd restart
